"""
drift_app.py
============
Streamlit Dashboard for ML-IDS Drift Monitoring.

Visualises data drift, prediction drift, and model performance
degradation over time. Reads drift reports generated by drift_monitor.py.

Paper: "Machine Learning-Based Intrusion Detection for Cloud Network Security:
        A Zero Trust Architecture Approach"
Author: Dingaan Mahlatse Machethe

Usage:
  streamlit run dashboard/drift_app.py
"""

import os
import sys
import json
import glob
import numpy as np
import pandas as pd
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT_DIR)

REPORTS_DIR = os.path.join(ROOT_DIR, "results", "drift_reports")

st.set_page_config(
    page_title="ML-IDS Drift Monitor",
    page_icon="🛡️",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_reports() -> list[dict]:
    """Load all drift report JSON files from the reports directory."""
    if not os.path.exists(REPORTS_DIR):
        return []
    files = sorted(glob.glob(os.path.join(REPORTS_DIR, "drift_report_*.json")))
    reports = []
    for f in files:
        with open(f) as fh:
            reports.append(json.load(fh))
    return reports


def load_summary() -> dict | None:
    """Load the drift summary if it exists."""
    path = os.path.join(REPORTS_DIR, "drift_summary.json")
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return None


def status_color(status: str) -> str:
    return {
        "STABLE": "green",
        "WARNING": "orange",
        "CRITICAL": "red",
    }.get(status, "grey")


def status_emoji(status: str) -> str:
    return {
        "STABLE": "✅",
        "WARNING": "⚠️",
        "CRITICAL": "🚨",
    }.get(status, "❓")


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

st.sidebar.title("🛡️ ML-IDS Drift Monitor")
st.sidebar.markdown("---")

reports = load_reports()
summary = load_summary()

st.sidebar.metric("Reports Available", len(reports))

if summary:
    st.sidebar.markdown("### Windows Tracked")
    for w in summary.get("windows", []):
        emoji = status_emoji(w["status"])
        st.sidebar.markdown(f"{emoji} **{w['window']}**: {w['status']}")

st.sidebar.markdown("---")
st.sidebar.caption(
    "PSI < 0.10 = Stable | 0.10–0.25 = Warning | > 0.25 = Critical"
)
st.sidebar.caption("Run `python src/drift_monitor.py --schedule` to generate reports.")

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

st.title("ML-IDS Zero Trust Cloud — Drift Monitoring")
st.markdown(
    "Monitors data drift, prediction drift, and model performance "
    "degradation for the intrusion detection system."
)

if not reports:
    st.warning(
        "No drift reports found. Generate them first:\n\n"
        "```bash\npython src/drift_monitor.py --schedule\n```"
    )
    st.stop()

# ---------------------------------------------------------------------------
# Row 1: Overall Status Cards
# ---------------------------------------------------------------------------

cols = st.columns(4)

latest = reports[-1]
fd = latest.get("feature_drift", {})
pd_info = latest.get("prediction_drift", {})
perf = latest.get("performance_drift", {})

with cols[0]:
    status = fd.get("overall_status", "UNKNOWN")
    st.metric(
        "Overall Status",
        f"{status_emoji(status)} {status}",
        delta=None,
    )

with cols[1]:
    drift_share = fd.get("drift_share", 0)
    n_drifted = fd.get("n_drifted", 0)
    n_total = fd.get("n_features", latest.get("n_features", 25))
    st.metric(
        "Features Drifted",
        f"{n_drifted}/{n_total}",
        delta=f"{drift_share:.0%}",
        delta_color="inverse",
    )

with cols[2]:
    if pd_info:
        delta_attack = pd_info.get("delta_attack_rate", 0)
        st.metric(
            "Attack Rate Shift",
            f"{pd_info['current']['attack_rate']:.1%}",
            delta=f"{delta_attack:+.1%}",
            delta_color="inverse" if pd_info.get("alert") else "normal",
        )
    else:
        st.metric("Attack Rate Shift", "N/A")

with cols[3]:
    if perf:
        acc_delta = perf.get("accuracy_delta", 0)
        st.metric(
            "Accuracy Delta",
            f"{perf['current']['accuracy']:.3f}",
            delta=f"{acc_delta:+.4f}",
            delta_color="normal" if acc_delta >= 0 else "inverse",
        )
    else:
        st.metric("Accuracy Delta", "N/A")

st.markdown("---")

# ---------------------------------------------------------------------------
# Row 2: Feature Drift Chart
# ---------------------------------------------------------------------------

st.subheader("Feature Drift (PSI)")

feature_data = fd.get("all_features", [])
if feature_data:
    df_features = pd.DataFrame(feature_data).head(15)

    fig = px.bar(
        df_features,
        x="feature",
        y="psi",
        color="status",
        color_discrete_map={
            "STABLE": "#22c55e",
            "WARNING": "#f59e0b",
            "CRITICAL": "#ef4444",
        },
        title="Top 15 Features by Population Stability Index (PSI)",
        labels={"psi": "PSI", "feature": "Feature"},
    )
    fig.add_hline(
        y=0.10, line_dash="dash", line_color="orange",
        annotation_text="Warning (0.10)",
    )
    fig.add_hline(
        y=0.25, line_dash="dash", line_color="red",
        annotation_text="Critical (0.25)",
    )
    fig.update_layout(height=450)
    st.plotly_chart(fig, use_container_width=True)

    # Full feature table
    with st.expander("View All Feature PSI Values"):
        st.dataframe(
            pd.DataFrame(feature_data),
            use_container_width=True,
            hide_index=True,
            column_config={
                "psi": st.column_config.NumberColumn(format="%.6f"),
            },
        )

# ---------------------------------------------------------------------------
# Row 3: Drift Over Time (if multiple windows)
# ---------------------------------------------------------------------------

if len(reports) > 1:
    st.markdown("---")
    st.subheader("Drift Progression Over Time")

    windows_data = []
    for r in reports:
        fd_r = r.get("feature_drift", {})
        windows_data.append({
            "window": r.get("window", "?"),
            "drift_share": fd_r.get("drift_share", 0),
            "n_drifted": fd_r.get("n_drifted", 0),
            "status": fd_r.get("overall_status", "STABLE"),
        })

    df_windows = pd.DataFrame(windows_data)

    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(
        x=df_windows["window"],
        y=df_windows["drift_share"],
        mode="lines+markers",
        name="Drift Share",
        line=dict(color="#3b82f6", width=3),
        marker=dict(size=10),
    ))
    fig2.add_hline(
        y=0.30, line_dash="dash", line_color="orange",
        annotation_text="Warning (30%)",
    )
    fig2.add_hline(
        y=0.50, line_dash="dash", line_color="red",
        annotation_text="Critical (50%)",
    )
    fig2.update_layout(
        title="Drift Share Across Time Windows",
        yaxis_title="Share of Drifted Features",
        xaxis_title="Time Window",
        yaxis_tickformat=".0%",
        height=400,
    )
    st.plotly_chart(fig2, use_container_width=True)

# ---------------------------------------------------------------------------
# Row 4: Prediction Drift
# ---------------------------------------------------------------------------

if pd_info:
    st.markdown("---")
    st.subheader("Prediction Distribution Drift")

    col_a, col_b = st.columns(2)

    with col_a:
        ref = pd_info["reference"]
        fig3 = go.Figure(data=[
            go.Pie(
                labels=["Normal", "Attack"],
                values=[ref["normal_rate"], ref["attack_rate"]],
                hole=0.4,
                marker_colors=["#22c55e", "#ef4444"],
            )
        ])
        fig3.update_layout(title="Reference (Training) Predictions", height=350)
        st.plotly_chart(fig3, use_container_width=True)

    with col_b:
        curr = pd_info["current"]
        fig4 = go.Figure(data=[
            go.Pie(
                labels=["Normal", "Attack"],
                values=[curr["normal_rate"], curr["attack_rate"]],
                hole=0.4,
                marker_colors=["#22c55e", "#ef4444"],
            )
        ])
        fig4.update_layout(title="Current (Production) Predictions", height=350)
        st.plotly_chart(fig4, use_container_width=True)

    if pd_info.get("alert"):
        st.error(f"🚨 {pd_info['message']}")
    else:
        st.success(f"✅ {pd_info['message']}")

# ---------------------------------------------------------------------------
# Row 5: Performance Drift
# ---------------------------------------------------------------------------

if perf:
    st.markdown("---")
    st.subheader("Model Performance Degradation")

    metrics_list = ["accuracy", "precision", "recall", "f1"]
    ref_vals = [perf["reference"].get(m, 0) for m in metrics_list]
    curr_vals = [perf["current"].get(m, 0) for m in metrics_list]

    fig5 = go.Figure()
    x_pos = list(range(len(metrics_list)))
    fig5.add_trace(go.Bar(
        x=metrics_list,
        y=ref_vals,
        name="Reference (Training)",
        marker_color="#3b82f6",
    ))
    fig5.add_trace(go.Bar(
        x=metrics_list,
        y=curr_vals,
        name="Current (Production)",
        marker_color="#f59e0b",
    ))
    fig5.update_layout(
        title="Reference vs Current Performance Metrics",
        yaxis_title="Score",
        yaxis_range=[0, 1],
        barmode="group",
        height=400,
    )
    st.plotly_chart(fig5, use_container_width=True)

    # Delta table
    deltas = {
        "Metric": ["Accuracy", "F1 Score"],
        "Delta": [
            perf.get("accuracy_delta", 0),
            perf.get("f1_delta", 0),
        ],
    }
    st.dataframe(
        pd.DataFrame(deltas),
        use_container_width=True,
        hide_index=True,
    )

# ---------------------------------------------------------------------------
# Footer
# ---------------------------------------------------------------------------

st.markdown("---")
st.caption(
    "ML-IDS Zero Trust Cloud | Drift Monitor v1.0 | "
    f"Last report: {latest.get('timestamp', 'N/A')}"
)
